-- Create ENUM type for account_type
CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');

-- Create classification table
CREATE TABLE IF NOT EXISTS public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT NULL,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);

-- Create inventory table
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    inv_make CHARACTER VARYING NOT NULL,
    inv_model CHARACTER VARYING NOT NULL,
    inv_year CHARACTER(4) NOT NULL,
    inv_description TEXT NOT NULL,
    inv_image CHARACTER VARYING NOT NULL,
    inv_thumbnail CHARACTER VARYING NOT NULL,
    inv_price NUMERIC(9,0) NOT NULL,
    inv_miles INTEGER NOT NULL,
    inv_color CHARACTER VARYING NOT NULL,
    classification_id INTEGER NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);

-- Add FK to classification
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id)
REFERENCES public.classification (classification_id) MATCH SIMPLE
ON UPDATE CASCADE
ON DELETE NO ACTION;

-- Create account table
CREATE TABLE IF NOT EXISTS public.account (
    account_id INTEGER NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname CHARACTER VARYING NOT NULL,
    account_lastname CHARACTER VARYING NOT NULL,
    account_email CHARACTER VARYING NOT NULL,
    account_password CHARACTER VARYING NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);

-- Insert classification rows
INSERT INTO public.classification (classification_name)
VALUES 
    ('Custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');

-- Insert inventory test data
INSERT INTO public.inventory
(inv_make, inv_model, inv_year, inv_description, inv_image, inv_thumbnail, inv_price, inv_miles, inv_color, classification_id)
VALUES 
    ('GM', 'Hummer', '2022', 'A GM Hummer with small interiors and 4WD.', '/images/hummer.jpg', '/images/hummer-thumb.jpg', 80000, 10000, 'Black', 3),
    ('Ford', 'Mustang', '2021', 'A classic Ford Mustang Sport car.', '/images/mustang.jpg', '/images/mustang-thumb.jpg', 55000, 8000, 'Red', 2);

-- Verify
SELECT * FROM public.inventory ORDER BY inv_id ASC;

-- #4 - Fix Hummer description
UPDATE inventory
SET inv_description = REPLACE(inv_description, 'small interiors', 'a huge interior')
WHERE inv_make = 'GM' AND inv_model = 'Hummer';

-- #6 - Fix image paths
UPDATE inventory
SET inv_image = REPLACE(inv_image, '/images/', '/images/vehicles/'),
    inv_thumbnail = REPLACE(inv_thumbnail, '/images/', '/images/vehicles/');
